### ISSUE TITLE
Feature request: support multiple Google App accounts

### ISSUE THREAD

**Issue by jc00ke** [borismasis/send-to-calendar#1]
Would be awesome to be able to choose which acct to import to. Right now (with any extension, even plain links) the event is opened in my default, personal acct, but 95% of the time I want it opened in my business app acct.

Thoughts?

**Comment by borismasis** [comment]
Hi Jesse, thanks for the comment. The calendar will open to your default primary account (which is the one you sign into first). You can switch your default account by signing out of all Google accounts, and then signing into your business account first. Alternatively, you could change background.js in the extension to reference http://www.google.com/calendar/b/1/event?action=TEMPLATE&text= instead of just http://www.google.com/calendar/event?action=TEMPLATE&text= and that will force open your secondary account instead of the primary one.

Hope this helps!

Cheers,
- Boris
